# Generated by Django 3.1.1 on 2020-09-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField()),
                ('end_time', models.DateField()),
                ('problem_type', models.IntegerField()),
                ('problem_state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=300, null=True)),
                ('option_vfield', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.option')),
                ('problem_vfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.problem')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='problem_ofield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.problem'),
        ),
    ]
