# Generated by Django 3.1.1 on 2020-09-08 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20200904_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('answer_num', models.IntegerField()),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='problem_state',
        ),
        migrations.CreateModel(
            name='QuestionProblem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.problem')),
                ('question_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.questionlist')),
            ],
        ),
    ]
