# Generated by Django 3.1.1 on 2020-09-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20200908_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='problem_ofield',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='option_vfield',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='problem_vfield',
            new_name='problem',
        ),
    ]
