# Generated by Django 3.1.1 on 2020-09-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20200911_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlist',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='questionlist',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
